apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-ztunnel
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
    app.kubernetes.io/component: mesh
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # ZTunnel CR không trong Git (bootstrap tay)
    argocd.argoproj.io/compare-options: ServerSideDiff=false
spec:
  project: banking-platform
  source:
    repoURL: https://github.com/kevinram164/cloud-native-platform.git
    targetRevision: main
    path: phase9-gitops-platform/mesh/ztunnel
  destination:
    server: https://kubernetes.default.svc
    namespace: ztunnel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      # SSA prune field spec.profile không có trên schema v1
    automated:
      prune: false
      selfHeal: true
