apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  profile: ambient
  values:
    # Lab: default 500m/2Gi không schedule trên worker (Insufficient cpu)
    global:
      defaultPodDisruptionBudget:
        enabled: false
    pilot:
      trustedZtunnelNamespace: ztunnel
      replicaCount: 1
      autoscaleEnabled: false
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    meshConfig:
      discoverySelectors:
        - matchLabels:
            istio-discovery: enabled
