apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - banking-namespace.yaml
  - kong-namespace.yaml
  - banking-peer-authentication.yaml
  - banking-authorization.yaml
  - banking-service-entries.yaml
  - kong-peer-authentication.yaml
  - kong-authorization.yaml
