apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/part-of: phase9-gitops
    banking-demo/environment: dev-ocp
    openshift.io/cluster-monitoring: "true"
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: opensearch-uid1000
  labels:
    banking-demo/environment: dev-ocp
    app.kubernetes.io/part-of: phase9-gitops
    app.kubernetes.io/component: logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
runAsUser:
  type: RunAsAny
runAsGroup:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - runtime/default
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
groups:
  - system:serviceaccounts:logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch
  namespace: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch-dashboards
  namespace: logging
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opensearch-dashboards
  namespace: logging
  labels:
    app.kubernetes.io/name: opensearch-dashboards
    app.kubernetes.io/part-of: phase9-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  host: logs-platform.apps.ocp01.npd.co
  to:
    kind: Service
    name: opensearch-dashboards
    weight: 100
  port:
    targetPort: 5601
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
