# Infra — Postgres, Redis, RabbitMQ, Kong, Strimzi Kafka (dev-k8s)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app-of-apps-dev-k8s
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
    platform/environment: dev-k8s
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/kevinram164/cloud-native-platform.git
    targetRevision: main
    path: phase9-gitops-platform/environments/dev-k8s/argocd/applications/infra
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
