# Postgres HA — Phase 5 (Bitnami), ns postgres
# Values: phase5-architecture-refactor/postgres-ha/values-postgres-ha.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-postgres
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
    app.kubernetes.io/component: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: banking-platform
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 15.5.32
      helm:
        releaseName: postgres-ha
        valueFiles:
          - $values/phase5-architecture-refactor/postgres-ha/values-postgres-ha.yaml
        values: |
          global:
            defaultStorageClass: nfs-csi
          primary:
            persistence:
              storageClass: nfs-csi
          readReplicas:
            persistence:
              storageClass: nfs-csi
    - repoURL: https://github.com/kevinram164/banking-demo.git
      targetRevision: dev-ocp
      ref: values
    # SCC postgres-uid1001 — Bitnami chạy UID 1001 + seccomp (sync-wave -1, trước chart)
    - repoURL: https://github.com/kevinram164/cloud-native-platform.git
      targetRevision: main
      path: phase9-gitops-platform/gitops-platform/manifests/postgres-prereq
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
