apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBbzCCARWgAwIBAgIUZRzrDlE8wsn1GSsmyDOyGs6ClAYwCgYIKoZIzj0EAwIw
    JTEjMCEGA1UEAwwacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjYwNjIz
    MDIyODEzWhcNMzYwNjIxMDIyODEzWjAlMSMwIQYDVQQDDBpyb290LmxpbmtlcmQu
    Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLgtnntn5YSx
    QYRGoXfukIxtrhFiJfUBhua7CbuGF6N7Md8GYgzuJqy1clmeEeGaRoCeBW/LgXCv
    pgSeIUp8U3WjIzAhMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMAoG
    CCqGSM49BAMCA0gAMEUCIQCEhubf+fehcLX4wD4MNT/Hy4LbhM+38Q7rouVpqXqr
    KAIgBhsfp5thTTxzDyfLU/hrNhP+N3jbJfSTJxu2VU8hB+E=
    -----END CERTIFICATE-----
