apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: npd-telegram
  namespace: npd-shop
  labels:
    app.kubernetes.io/part-of: npd-monitoring
    alertmanagerConfig: aiops
spec:
  route:
    receiver: telegram
    groupBy:
      - alertname
    groupWait: 0s
    groupInterval: 1m
    repeatInterval: 30m
  receivers:
    - name: telegram
      telegramConfigs:
        - botToken:
            name: alertmanager-telegram
            key: bot-token
          chatID: -1004489182185
          parseMode: HTML
          sendResolved: true
          message: '{{ .CommonLabels.alertname }} [{{ .Status }}] {{ .CommonAnnotations.summary }}'
