apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor-route.yaml
  - jenkins-route.yaml
  - vault-route.yaml
  - argocd-route.yaml
  - coroot-route.yaml
  - keycloak-route.yaml
  - kafka-ui-route.yaml
  - banking-kong-proxy-ext.yaml
  - banking-route-frontend.yaml
  - banking-route-api.yaml
  - banking-route-ws.yaml
  - kong-route.yaml
